### ISSUE TITLE
[feature request] ConsoleLogWriter should write to the standard error output

### ISSUE THREAD

**Issue by feederiken9** [zio/zio-logging#136]
Currently, `SimpleConsoleLogWriter` and `ColoredLogWriter` output log messages the the standard output of the console. It would be more in-line with other logging frameworks, and more helpful IMHO to direct them to the dedicated error console also known as `StdErr`.

AFAICT this can be achieved by simply changing the 2 calls to `zio.console.putStrLn` in `LogWriter.scala` to `zio.console.putStrLnErr`. (zio/zio#3925)

**Comment by pshemass** [comment]
@feederiken9 do you want to open PR for that?

**Comment by feederiken9** [comment]
@pshemass would rather not. Signing a CLA under a pseudonym seems like more trouble than it's worth, it would be better for everyone if an established contributor looked into it.

**Comment by pshemass** [comment]
@feederiken9 fair enough. Problem is that I'm the only "established contributor" but I don't have time recently for this project. I will do my best anyway to address that.

**Comment by pshemass** [comment]
@feederiken9 I opened PR #139 that should allow you to do this. I'm not sure that this should be default.

```
ZLayer.requires[Console with Clock] ++ 
LogAppender.consoleErr(LogLevel.Info, LogFormat.SimpleConsoleLogFormat((_, s) => s)) >>> 
Logging.makeWithTimestamp(Some("myApp"))
```

**Comment by pshemass** [comment]
close by #139

```scala
Logging.consoleErr(
  level = LogLevel.Info, 
  format = LogFormat.ColoredLogFormat()
) >>> Logging.withRootLoggerName("my-component")
```
