### ISSUE TITLE
Could you please explain me a little bit of your design?

### ISSUE THREAD

**Issue by zhiwilliam** [zio/zio-logging#184]
Hey, I just quickly reviewed your code and a little bit be shocked!  I didn't find and monad in your core code. I saw a class called writer, but when I clicked in, I saw java io writer? It seems nobody knows functional programming log is made by writer monad? John provided state monad already and you can easily turn it as a good writer for logging. Maybe I am wrong but seems this is zio official site and why I cannot find a FP logger?

**Comment by pshemass** [comment]
@zhiwilliam we know about writer monad and other monads too. Believe me :) 

@jdegoes could you weight in.

**Comment by jdegoes** [comment]
Writer monad (`(w, a)` for `Monoid w`) is not practical for logging, as logging must handle infinite processes, and must make best-effort guarantee that maximal log information is preserved.

The writer monad is really only practical for finite computations whose "logs" can be safely discarded without negative impact on the business (e.g. timings and metrics for a query phase, for example).

You can get that from `ZPure` in ZIO Prelude, if that's more what you're looking for.
