### ISSUE TITLE
Provide a ZManaged variant of locally 

### ISSUE THREAD

**Issue by vigoo** [zio/zio-logging#210]
It would be nice to be able to apply log annotations when constructing a managed resource using logging in the acquire/release effects.

```scala
log.locallyManaged(LogAnnotations.Name("x" :: Nil)) {
  ZManaged.make(log.info("x"))(_ => log.info("y")).use { _ => log.info("z") }
}
```
all three log lines should have the applied annotations

**Comment by kubukoz** [comment]
Pretty sure that's how `locally` works right now, isn't it? All the lines are in the "enriched" context.

Unless `use` would be outside of `locallyManaged`, like:

```scala
log.locallyManaged(LogAnnotations.Name("x" :: Nil)) {
  ZManaged.make(log.info("x"))(_ => log.info("y"))
}.use { _ => log.info("z") }
```

because yeah, that would be cool :)

**Comment by pshemass** [comment]
@vigoo `acquire` and `release` part is pretty easy to implement with `Reservation` but `use` is close to impossible with current `ZManaged`

``` 
  def locallyManaged[R1, E, A1](f: LogContext => LogContext)(managed: ZManaged[R1, E, A1]): ZManaged[R1, E, A1] =
    ZManaged.makeReserve(managed.reserve.map(r => r.copy(locally(f)(r.acquire), exit => locally(f)(r.release(exit)))))
```

do you think is still worth to add it?

**Comment by pshemass** [comment]
added `locallyManaged` in #276.
