### ISSUE TITLE
Idea: ability to dump logging context into MDC on arbitrary effect

### ISSUE THREAD

**Issue by kubukoz** [zio/zio-logging#234]
Hi!

Sometimes you have to wrap a classic Scala library / a Java library which uses slf4j directly. Sadly, in these situations, the context of a logger will never reach MDC, so you won't see anything unless you explicitly wrap the interop with something roughly like:

```scala
def withLoggingContext[A](eff: => A): ZIO[Logging, Throwable, A] =
  log.context.flatMap { ctx =>
    ZIO.effect {
      import scala.jdk.CollectionConverters._
      val previous =
        Option(MDC.getCopyOfContextMap().asScala)
          .getOrElse(Map.empty[String, String])

      try {
        ctx.renderContext.foreach((MDC.put _).tupled)
        eff
      } finally MDC.setContextMap(previous.asJava)
    }
  }
```

I don't know that much about what ZIO lets us do in this situation, but do you think this would be possible to do automatically on every `effect` / `effectAsync`, e.g. with a custom executor that accesses the logger's `FiberRef` somehow and dumps its variables to MDC?

**Comment by pshemass** [comment]
@kubukoz this sound pretty hacky :) I'm not aware of any solution for that but let ask @jdegoes and @mijicd

**Comment by kubukoz** [comment]
Of course it's hacky, it's MDC ;)

**Comment by pshemass** [comment]
sorry but no solution for that
