### ISSUE TITLE
Construct logging layer within effectful computation.

### ISSUE THREAD

**Issue by meadofpoetry** [zio/zio-logging#239]
Since `ZLayer` is not a monad, I have real troubles with creating a logging layer.

All the methods which allow to create a logging layer are similar to:

```
def console(
    logLevel: LogLevel = LogLevel.Info,
    format: LogFormat[String] = LogFormat.ColoredLogFormat((_, s) => s)
  ): ZLayer[Console with Clock, Nothing, Logging]
```

Now, consider I would like to read `logLevel` from the config file or environment variable. It would be an effectful computation (or a layer), but since I can't lift `ZLayer`, there is no `flatMap` or something, I can't construct `ZLayer[Logging]` from `Task[LogLevel]` or `ZLayer[Config]`. Or do I miss something?

**Comment by pshemass** [comment]
Yes `ZLayer` is not a monad but scenario that you describe can be handle with `Logging.modifyLoggerM`

```
def logLevelFromConfig[A](logger: Logger[A]): URIO[Has[MyConfig], Logger[A]] =
    getConfig[MyConfig].map(config => logger.derive(LogAnnotation.Level(config.logLevel)))

Logging.console() >>> Logging.modifyLoggerM(logLevelFromConfig)
```
probably we should provide `withContextM` to streamline this a little bit.

Let me know if that helps

**Comment by meadofpoetry** [comment]
Thanks, that's precisely what I want.
