### ISSUE TITLE
FR: slf4j bridge improvement

### ISSUE THREAD

**Issue by virusdave** [zio/zio-logging#240]
Slf4j docs show a pattern of using `{}` in log format message (see http://www.slf4j.org/manual.html#typical_usage)
However, the bridge implementation uses `String.format` everywhere (see eg. https://github.com/zio/zio-logging/blob/master/slf4j-bridge/src/main/scala-2/org/slf4j/impl/ZioLogger.scala#L20), which doesn't substitute the arguments' `.toString` result in place of that when logging.  The result for many cases is logs filled with stuff like `org.eclipse.jetty.util.component.AbstractLifeCycle] STARTED @{}ms {}`, which is less than helpful :)

Please support positional arguments?  Perhaps just replacing `{}` by `%s` in the format string would be sufficient?

**Comment by jdegoes** [comment]
The SLF4J bridge needs to be created in the 2.0 branch. Hopefully this ticket can incorporated into the redesign.

**Comment by justcoon** [comment]
fixed in #482
