### ISSUE TITLE
Release compiled for Scala 3

### ISSUE THREAD

**Issue by lxwbr** [zio/zio-logging#274]
Currently having an issue with using `zio-logging` Scala 2 version and the `zio` Scala 3 version together in a Scala 3 project. The error I receive is:
```
[error] An existential type that came from a Scala-2 classfile cannot be
[error] mapped accurately to to a Scala-3 equivalent.
[error] original type    : (S[X], X => cats.free.Free[S, A]) forSome X
[error] reduces to       : (S[X], X => cats.free.Free[S, A])
[error] type used instead: (S[Any], Any => cats.free.Free[S, A])
[error] This choice can cause follow-on type errors or hide type errors.
[error] Proceed at own risk.
[error] one error found
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```
Unfortunately I cannot use `zio` Scala 2 compiled version for another issue with `Tag` in that version of `zio`. Do you plan to release a Scala 3 version of `zio-logging` anytime soon?

**Comment by cilicio** [comment]
Waiting for this too.

**Comment by pshemass** [comment]
0.5.9 with Scala 3.0 on the way
