### ISSUE TITLE
Add support for logging Throwable as warning

### ISSUE THREAD

**Issue by erdeszt** [zio/zio-logging#333]
I would like to log a message as a warning and include an exception in the log. So similar to the:
```scala
def error(line: => String, cause: Cause[Any])
```
I'd like to have a:
```scala
def warn(line: => String, cause: Cause[Any]) 
```
That would log at the `Warn` level but it would include the error trace similarly to `error`. 

If this is already possible and I just missed it somehow I'm sorry, otherwise if there's no objection I'd be happy to work on a PR for this.

**Comment by pshemass** [comment]
Go ahead and open PR for this.
