### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by pshemass** [zio/zio-logging#359]
We need better documentation :)

**Comment by jdegoes** [comment]
We need a whole microsite, as well as documentation!

**Comment by francisdb** [comment]
Just some example code in the readme on how to use this in ZIO2 would already help a lot.

**Comment by justcoon** [comment]
i am working on documentation and some examples

**Comment by justcoon** [comment]
i will continue to work on documentations improvements during [ZIO Hackathon 2022 - New York City](https://github.com/orgs/zio/projects/6)
