### ISSUE TITLE
Provide version for zio-2.0.0-M6-2

### ISSUE THREAD

**Issue by domdorn** [zio/zio-logging#382]
I'm _trying_ to migrate a small service to zio 2 M6-2 to figure out what needs to be done.. 
Looks like the new baked-in logging implementation is not yet capable of handling the equivalent of `locally`... so at least for my projects, I'll probably have to rely on a version of zio-logging for zio-2. 
would be great if we could have a first version for those of us that used zio-logging in 1.x and can't simply migrate to the new logging version cause of missing features.

**Comment by pshemass** [comment]
It’s work in progress. In `zio2` branch you will find code that but it’s not released just yet.

I wait for John to review https://github.com/zio/zio-logging/pull/363 hopefully this week we will push this.

**Comment by jdegoes** [comment]
We have the code, we just need a release for `ZIO-2.0-RC1`. Hopefully this week!
