### ISSUE TITLE
Unsafe Logging (without ZIO dependency)

### ISSUE THREAD

**Issue by tusharmath** [zio/zio-logging#389]
I am thinking of adding some logging to ZIO Http's backend. The purpose is to help debug issues in the library as a contributor and also as a consumer of the library I would sometime want to know what's going on behind the scenes.

A lot of the backend doesn't run on ZIO or FP, so it's a bit hard to use ZIO Logging for such type of code. eg:

```scala
trait ChannelHandler {
  override def channelRead(ctx: ChannelHandlerContext, msg: Any): Unit = {
    Logger.debug("Message refCount: ${msg.refCount()}") // returns a ZIO, doesn't log anything

   // .. .. 

   Logger.debug("Message refCount: ${msg.refCount()}") // returns a ZIO, doesn't log anything
  }
}
```

**Proposal**
Support and `UnsafeLogger` that logs without depending on `ZIO`.

**Comment by jdegoes** [comment]
I think we have to close this now as it no longer makes sense in ZIO 2.0. ZIO Logging ties into the hooks of ZIO to get access to file, class, fiber id, etc., and is not likely to be a good fit for impure logging. We could integrate impure logging, but then it would not be able to access ZIO internal details such as the above. So better to rely on a first-class Java solution for this.

Please re-open if you feel differently after looking at the new 2.0 design.
