### ISSUE TITLE
Wrong logger used for uncaught failures

### ISSUE THREAD

**Issue by kluen** [zio/zio-logging#444]
Hi, I tried get my application to only log through SLF4J with the latest RC versions of zio and zio-logging. It works fine so far except for one use case: When the application, which is created with `ZIOAppDefault`, crashes without catching any error, I would still expect the output to be logged through SLF4J. However, it uses ZIO's built-in logger instead although it is deactivated.

Not entirely sure if this behaviour is by design, but in a production environment I would really appreciate it if all logs use the same format without any extra boilerplate code like tapping or catching in the effect.

Here is some scala-cli code to reproduce the issue:
```
//> using scala "2.13"
//> using lib "dev.zio::zio:2.0.0-RC5"
//> using lib "dev.zio::zio-logging:2.0.0-RC8"
//> using lib "dev.zio::zio-logging-slf4j:2.0.0-RC8"
//> using lib "ch.qos.logback:logback-classic:1.2.11"

import zio._
import zio.logging.backend._

object App extends ZIOAppDefault {
  def run = ZIO.withRuntimeConfig(defaultLoggerDisabled @@ slf4jLogging)(program)

  lazy val defaultLoggerDisabled = RuntimeConfig.default.copy(logger = ZLogger.none)
  lazy val slf4jLogging = SLF4J.slf4j(LogLevel.Info)

  lazy val program = ZIO.logInfo("Hey there!") *> ZIO.attempt(throw new RuntimeException("Oh no!"))
}

App.main(Array()) // ignore this line, it is just here to work around a scala-cli bug which prevents ZIO apps from being run
```

The output produced:
```
16:54:25.716 [ZScheduler-12] INFO zio-slf4j-logger - timestamp=2022-04-20T16:54:25.661218+02:00 level=INFO thread=zio-fiber-2 message="Hey there!"
timestamp=2022-04-20T14:54:25.742614Z level=ERROR thread=#zio-fiber-0 message="" cause="Exception in thread "zio-fiber-2" java.lang.RuntimeException: java.lang.RuntimeException: Oh no!
	at <empty>.Main.App.program(Main.scala:21)
	at <empty>.Main.App.run(Main.scala:16)"
```

The first log entry shows that SLF4J logging works, the second shows logging through the built-in logger.

**Comment by alphaho** [comment]
@kluen I think this issue should be raised in zio/zio instead

**Comment by domdorn** [comment]
//cc @adamgfraser

**Comment by adamgfraser** [comment]
See zio/zio#6714.
