### ISSUE TITLE
Allow the cause to be logged

### ISSUE THREAD

**Issue by Ellzord** [zio/zio-logging#452]
Currently it isn't possible to access the `Cause` with `LogFormat`. It isn't also extensible enough to do that (due to `LogFormat.make()` being private).

We should consider adding `Cause` in `LogFormat.default` but at the very least add the ability to combine it in with `|-|` (add `val cause` to the companion object).

**Comment by justcoon** [comment]
Hi @Ellzord, 

`LogFormat.cause` was added, but for now, it is not part of `LogFormat.default`

you can create own one 

```
val logFormatWithCause = LogFormat.default |-| LogFormat.cause
```

let us know if this is solving this issue ...

thanks

**Comment by Ellzord** [comment]
LGTM
