### ISSUE TITLE
provide example on how to test logging messages

### ISSUE THREAD

**Issue by domdorn** [zio/zio-logging#462]
The documentation should have a example on how to use the loggers in tests and how to do assertions on log messages.

**Comment by justcoon** [comment]
Hi @domdorn,

with ZIO 2, logging interface is in zio core library, 
you can use [ZTestLogger](https://github.com/zio/zio/blob/series/2.x/test/shared/src/main/scala/zio/test/ZTestLogger.scala)

to test log output, please check that, and let us know if this is what your are looking for,

also in addition thank you for your hint, definitely it should be in documentation, we will work on that ...

**Comment by justcoon** [comment]
Hi @domdorn, please let me know if this solving your problem, thank you very much.

**Comment by domdorn** [comment]
sadly we've deleted all code that tests log output from our tests, so can't reproduce this now anymore :-/
