### ISSUE TITLE
Slf4jBridge logs are missing arguments

### ISSUE THREAD

**Issue by mhodovaniuk** [zio/zio-logging#482]
With Slf4jBridge.initialize, logs from Slf4j loggers are missing arguments.
`org.slf4j.impl.ZioLogger` logs as `run(ZIO.logInfo(String.format(format, arg)))`, but Slf4j loggers use `{}` as argument placeholder. As a result `String.format(format, arg)` ignores `{}` and message does not contain `arg` information.

**Comment by justcoon** [comment]
hi @mhodovaniuk, thank you for report, we will check it
