### ISSUE TITLE
Check if Throwables are null

### ISSUE THREAD

**Issue by gkfabs** [zio/zio-logging#510]
In log functions ([debug](https://github.com/zio/zio-logging/blob/144b77c734937d69eda15145a93e538433a008ef/slf4j-bridge/src/main/scala-2/org/slf4j/impl/ZioLogger.scala#L45), [trace](https://github.com/zio/zio-logging/blob/144b77c734937d69eda15145a93e538433a008ef/slf4j-bridge/src/main/scala-2/org/slf4j/impl/ZioLogger.scala#L26), etc...) we never check if the throwable is null. We could then use the pure string version ([debug](https://github.com/zio/zio-logging/blob/144b77c734937d69eda15145a93e538433a008ef/slf4j-bridge/src/main/scala-2/org/slf4j/impl/ZioLogger.scala#L33), [trace](https://github.com/zio/zio-logging/blob/144b77c734937d69eda15145a93e538433a008ef/slf4j-bridge/src/main/scala-2/org/slf4j/impl/ZioLogger.scala#L14), etc...)

It seems to be a common practice in java library where those functions can be used with a null throwable ([netty](https://github.com/aws/aws-sdk-java-v2/blob/master/http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/utils/NettyClientLogger.java#L58))

**Comment by justcoon** [comment]
hi @gkfabs , thanks for report, we will add check for that ...
