### ISSUE TITLE
Support slf4j markers in SLF4J backend

### ISSUE THREAD

**Issue by jeejeeone** [zio/zio-logging#520]
Support slf4j `org.slf4j.Marker` in SLF4J backend. Currently slf4j Marker API cannot be used with zio-logging-slf4j SLF4J backend. This is inconvenient in some use cases, for example when using an ECS Layout with `includeMarkers`.

For example write info log in current implementation:
`slf4jLogger.info(message.toString, throwable)`

It should be possible to pass `org.slf4j.Marker` to SLF4J appender, used slf4j api methods should use marker if applicable.

Info log with marker:
`slf4jLogger.info(marker, message.toString, throwable)`

Should also be applied to is--Enabled methods:
`slf4jLogger.isTraceEnabled(marker)`

**Comment by justcoon** [comment]
hi @jeejeeone, I made draft PR #521, please check it and let me know, what do you think about that ...

**Comment by jeejeeone** [comment]
@justcoon Hello, looks good to me! My use case with ECS layout and includeMarkers works ok and the API is nice.

**Comment by justcoon** [comment]
@jeejeeone , thanks you for answer

Just for clarity (i mentioned there 2 variants), for your use case:
2. variant where, there is log marker name provided
`val confidentialMarker = SLF4J.logMarkerName("CONFIDENTIAL")`

Do you think that variant? I like it more, it look nicer, but may be limitation for some very specific use cases, where somebody  like to provide custom Marker implementation

**Comment by jeejeeone** [comment]
In my previous reply I was referring to the second variant :-) Yeah, it's nice, not sure about custom Marker implementations.
