### ISSUE TITLE
`zio.logging.LogAnnotation` does not work when `version > 2.0.1`

### ISSUE THREAD

**Issue by stivens** [zio/zio-logging#553]
`??? |-| annotation(LogAnnotation.TraceId)` doesnt display any trace id. Downgrading to 2.0.1 "resolves" the problem

**Comment by justcoon** [comment]
Hi @stivens, 
thanks for your report, can you add some details? Which logging layer are you using?

Thank you very much

**Comment by stivens** [comment]
Hi @justcoon 
Im using SL4J backend

```
val ZIOVersion                    = "2.0.3"
val ZIOLoggingVersion       = "2.1.3"
libraryDependencies ++= Seq(
  "dev.zio"               %% "zio"                              % ZIOVersion,
  "dev.zio"               %% "zio-logging"                % ZIOLoggingVersion,
  "dev.zio"               %% "zio-logging-slf4j"        % ZIOLoggingVersion,
```

**Comment by justcoon** [comment]
Hi @stivens,

that part changed with version `2.1.0` for slf4j, 

please check https://github.com/zio/zio-logging/blob/master/docs/slf4j.md

if you will have some additional question, or something will be unclear, please let me know

thank you

**Comment by stivens** [comment]
Given:

```scala
object Slf4jSimpleApp extends ZIOAppDefault {

  private val logger = Runtime.removeDefaultLoggers >>> SLF4J.slf4j(
    format = {
      import zio.logging.LogFormat._

      label("timestamp", timestamp.fixed(32)).color(LogColor.WHITE) |-|
        label("level", level).highlight |-|
        annotation(LogAnnotation.TraceId) |-|
        label("message", quoted(line)).highlight |-|
        label("thread", fiberId).color(LogColor.WHITE)
    },
    loggerName = _ => "nfs-zio-logger"
  )

  private val users = List.fill(2)(UUID.randomUUID())

  override def run: ZIO[Scope, Any, ExitCode] =
    (for {
      _       <- ZIO.logInfo("Start")
      traceId <- ZIO.succeed(UUID.randomUUID())
      _ <- ZIO.foreachPar(users) { _ =>
        {
          ZIO.logInfo("Starting user operation") *>
            ZIO.logInfo("Stopping user operation")
        }
      } @@ LogAnnotation.TraceId(traceId)
      _ <- ZIO.logInfo("Done")
    } yield ExitCode.success).provideLayer(logger)
}
```

output:
```
timestamp2022-11-09T11:04:52.814608+01:00 levelINFO  message"Start" threadzio-fiber-4
timestamp2022-11-09T11:04:52.851507+01:00 levelINFO  message"Starting user operation" threadzio-fiber-6
timestamp2022-11-09T11:04:52.852603+01:00 levelINFO  message"Stopping user operation" threadzio-fiber-6
timestamp2022-11-09T11:04:52.851517+01:00 levelINFO  message"Starting user operation" threadzio-fiber-5
timestamp2022-11-09T11:04:52.865968+01:00 levelINFO  message"Stopping user operation" threadzio-fiber-5
timestamp2022-11-09T11:04:52.871573+01:00 levelINFO  message"Done" threadzio-fiber-4
```

---------------

What else should I setup?

**Comment by stivens** [comment]
Update: Okay it does work when I put `trace_id=%X{trace_id}` into logback configuration.

Anyway, it should work when passed as constructor argument as well

**Comment by stivens** [comment]
Maybe SLF4J constructor should not accept "generic" LogFormat then? I think it is kinda confusing

**Comment by justcoon** [comment]
yes, it is confusing, but also opening place for customisations, 

in general, we will work on documentations improvements

and also think about how to clarify or improve  it more, to have it more clear

with latest release (2.1.4), is it ok for you?

**Comment by stivens** [comment]
> with latest release (2.1.4), is it ok for you?

Do you mean #555?

**Comment by justcoon** [comment]
Hi @stivens,

> Do you mean https://github.com/zio/zio-logging/pull/555?

yes, i mean also this one,  

considering discussion here, I was not sure what else remaining here

considering `zio.logging.LogAnnotation`, as I mentioned, in current implementation they are going to MDC, and if you do not have in specific logger backend format MDC setup, they will not be visible

I do not think that it is possible to know in common zio-logging-slf4j implementation, how specific slf4j logging backend is configured and based on that do some decisions (if you have some idea, i will be glad if you share that)
 
but probably by some configuration we can do, that `zio.logging.LogAnnotation` will be placed to message, but this again will probably require some custom setup

**Comment by stivens** [comment]
>  in current implementation they are going to MDC

This behaviour is fine. Or even great I would say.

The only issue is that SL4J factory accepts LogFormat which is not compatible with it. Maybe it should accept some other type instead? So it will be customizable but not misleading.

BTW. Thank you! :)
