### ISSUE TITLE
Support SLF4J 2.0.x for slf4j-bridge

### ISSUE THREAD

**Issue by Marc-Ducret** [zio/zio-logging#567]
If any other library depends on `slf4j-api` 2.0.x, the StaticLoggerBinder approach will not work as it is no longer supported in such versions of SLF4J. See https://www.slf4j.org/codes.html#ignoredBindings.

In this case such warnings would be printed:
```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/home/user/.cache/coursier/v1/https/repo1.maven.org/maven2/dev/zio/zio-logging-slf4j-bridge_2.13/2.1.3/zio-logging-slf4j-bridge_2.13-2.1.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
```
And therefore logs sent to SLF4J are then simply ignored.

**Comment by justcoon** [comment]
Hi @Marc-Ducret , 

thank you for report

I briefly check that, and it is look like that specific implementation for slf4j 2.0.x will be needed
