### ISSUE TITLE
logErrorCause does not show nested/suppressed/chained exceptions

### ISSUE THREAD

**Issue by frevib** [zio/zio-logging#569]
### Current behaviour:

`logErrorCause(message: => String, cause: => Cause[Any])` only logs the last exception message and stack trace in the exception chain.

### Desired behaviour:

`logErrorCause(message: => String, cause: => Cause[Any])` should log the last exception message with stack trace, **including all nested/suppressed/chained exceptions with their stack traces**

### Example

comment out one of the `.catchAllxxx` below to run

```scala
object Main extends ZIOAppDefault {
  
  case class FirstException(message: String) extends Exception(message)

  case class SecondException(message: String, cause: Throwable) extends Exception(message, cause)

  case class ThirdException(message: String, cause: Throwable) extends Exception(message, cause)

  val triggerException = ZIO.fail(FirstException("First Exception message"))
    .mapError(err => SecondException("Second exception message", err))
    .mapError(err => ThirdException("Third exception message", err))
  
  override def run: ZIO[Any with ZIOAppArgs with Scope, Any, Any] = {
    triggerException
      .catchAll(err => ZIO.succeed(err.printStackTrace()))
      .catchAllCause(err => ZIO.logErrorCause("log with ZIO Cause", err)) 
      .catchAllTrace {
        case (ex, trace) => ZIO.logErrorCause("log with ZIO Cause and trace", Cause.die(ex, trace))
      }
      .exitCode
  }
}
```

### Example explanation

`.catchAll(err => ZIO.succeed(err.printStackTrace()))` will print the "raw" stack trace, including nested exceptions. We want this, but then with the ZIO trace, not the "raw" trace:

```
Main$ThirdException: Third exception message
	at Main$.$anonfun$triggerException$3(Main.scala:15)
	at zio.Cause.$anonfun$map$1(Cause.scala:349)
	at zio.Cause.$anonfun$flatMap$2(Cause.scala:155)
	at zio.Cause$$anon$1.failCase(Cause.scala:178)
...
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:889)
...
	at zio.internal.FiberRuntime.run(FiberRuntime.scala:140)
	at zio.internal.ZScheduler$$anon$3.run(ZScheduler.scala:424)
Caused by: Main$SecondException: Second exception message
	at Main$.$anonfun$triggerException$2(Main.scala:14)
	... 28 more
Caused by: Main$FirstException: First Exception
	at Main$.$anonfun$triggerException$1(Main.scala:13)
	at zio.ZIO$.$anonfun$fail$1(ZIO.scala:3021)
	at zio.ZIO$.$anonfun$failCause$1(ZIO.scala:3027)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:986)
	... 16 more
```

`.catchAllCause(err => ZIO.logErrorCause("log with ZIO Cause", err))` will print only the last exception ("Third exception message") in the chain. **Here we would expect also the nested exceptions, but this is not the case**:

```
imestamp=2022-11-19T19:22:38.187461482Z level=ERROR thread=#zio-fiber-6 message="log with ZIO Cause" cause="Exception in thread "zio-fiber-6" Main$ThirdException: Main$ThirdException: Third exception message
	at <empty>.Main.triggerException(Main.scala:13)
	at <empty>.Main.triggerException(Main.scala:14)
	at <empty>.Main.triggerException(Main.scala:15)
	at <empty>.Main.run(Main.scala:20)
	at <empty>.Main.run(Main.scala:24)" location=<empty>.Main.run file=Main.scala line=20
```

`catchAllTrace {
        case (ex, trace) => ZIO.logErrorCause("log with ZIO Cause and trace", Cause.die(ex, trace))
      }
` does print the last exception, and all nested exceptions.

```timestamp=2022-11-19T19:23:04.063443332Z level=ERROR thread=#zio-fiber-6 message="log with ZIO Cause and trace" cause="Exception in thread "zio-fiber-6" Main$ThirdException: Third exception message
	at Main$.$anonfun$triggerException$3(Main.scala:15)
	at <empty>.Main.triggerException(Main.scala:13)
	at <empty>.Main.triggerException(Main.scala:14)
	at <empty>.Main.triggerException(Main.scala:15)
	at <empty>.Main.run(Main.scala:21)
	at <empty>.Main.run(Main.scala:24)
	Suppressed: Main$SecondException: Second exception message
		at Main$.$anonfun$triggerException$2(Main.scala:14)
		Suppressed: Main$FirstException: First Exception
			at Main$.$anonfun$triggerException$1(Main.scala:13)" location=<empty>.Main.run file=Main.scala line=22
```

**Comment by justcoon** [comment]
Hi @frevib ,

this does not look like `zio-logging` project issue,

just for clarity

zio-logging project contains backends for zio `ZLogger`, which is defined in [zio](https://github.com/zio/zio)

i am not sure which exact version if zio you are using

but I tried to compile your example with zio 2.0.3

and have following error

```
 This error handling operation assumes your effect can fail. However, your effect has Nothing for the error type, which means it cannot fail, so there is no need to handle the failure. To find out which method you can use instead of this operation, please see the reference chart at: https://zio.dev/can_fail
[error]       .catchAllTrace {
[error]                      ^
```

considering your program (and my knowledge)

```scala
 triggerException
      .catchAll(err => ZIO.succeed(err.printStackTrace()))
      .catchAllCause(err => ZIO.logErrorCause("log with ZIO Cause", err)) 
      .catchAllTrace {
        case (ex, trace) => ZIO.logErrorCause("log with ZIO Cause and trace", Cause.die(ex, trace))
      }
```

first catchAll `.catchAll(err => ZIO.succeed(err.printStackTrace()))`  will "recover" from error, so next `catchAll*`, do nothing

in addition to that zio wrapping Throwables to `Cause`  type, and then Cause is printed, in case of zio core default logger (`Cause.prettyPrint`), and this is not completely same like Throwable stack trace

not sure if my response will answer your question

if not, I recommend to you ask in zio discord, or create issue in zio core project

thank you, best regards

**Comment by frevib** [comment]
Hi,

I put all three `catchAllxxx` below each other, to show the different behaviours. Use the first one `.catchAll(err => ZIO.succeed(err.printStackTrace()))` to show the first example, e.g.:

```scala 
object Main extends ZIOAppDefault {
  
  case class FirstException(message: String) extends Exception(message)

  case class SecondException(message: String, cause: Throwable) extends Exception(message, cause)

  case class ThirdException(message: String, cause: Throwable) extends Exception(message, cause)

  val triggerException = ZIO.fail(FirstException("First Exception message"))
    .mapError(err => SecondException("Second exception message", err))
    .mapError(err => ThirdException("Third exception message", err))
  
  override def run: ZIO[Any with ZIOAppArgs with Scope, Any, Any] = {
    triggerException
      .catchAll(err => ZIO.succeed(err.printStackTrace()))
      .exitCode
  }
}
```

Use the second one for the second example:

```scala
object Main extends ZIOAppDefault {
  
  case class FirstException(message: String) extends Exception(message)

  case class SecondException(message: String, cause: Throwable) extends Exception(message, cause)

  case class ThirdException(message: String, cause: Throwable) extends Exception(message, cause)

  val triggerException = ZIO.fail(FirstException("First Exception message"))
    .mapError(err => SecondException("Second exception message", err))
    .mapError(err => ThirdException("Third exception message", err))
  
  override def run: ZIO[Any with ZIOAppArgs with Scope, Any, Any] = {
    triggerException
      .catchAllCause(err => ZIO.logErrorCause("log with ZIO Cause", err)) 
      .exitCode
  }
}
```

Last example:

```scala
object Main extends ZIOAppDefault {
  
  case class FirstException(message: String) extends Exception(message)

  case class SecondException(message: String, cause: Throwable) extends Exception(message, cause)

  case class ThirdException(message: String, cause: Throwable) extends Exception(message, cause)

  val triggerException = ZIO.fail(FirstException("First Exception message"))
    .mapError(err => SecondException("Second exception message", err))
    .mapError(err => ThirdException("Third exception message", err))
  
  override def run: ZIO[Any with ZIOAppArgs with Scope, Any, Any] = {
    triggerException
      .catchAllTrace {
        case (ex, trace) => ZIO.logErrorCause("log with ZIO Cause and trace", Cause.die(ex, trace))
      }
      .exitCode
  }
}
```

My question is: 

why does `catchAllCause(err => ZIO.logErrorCause("log with ZIO Cause", err))` not log `SecondException` and `FirstException`, but only `ThirdException` ?

**Comment by justcoon** [comment]
hi,

i think that

.catchAllCause(err => ZIO.logErrorCause("log with ZIO Cause", err)) 

is equal to

      .catchAllTrace {
        case (ex, trace) => ZIO.logErrorCause("log with ZIO Cause and trace", Cause.fail(ex, trace))
      }

there is Cause.fail vs Cause.die, and there are some differences (not sure how this is applied in specific cases ... , and why is not Throwable like Cause.die, maybe there is some bug in zio core library)

those are function definitions (in zio core project)
``` 
  def die(defect: Throwable, trace: StackTrace = StackTrace.none): Cause[Nothing]      = Die(defect, trace)
  def fail[E](error: E, trace: StackTrace = StackTrace.none): Cause[E]                 = Fail(error, trace)
```
where `die` have it like Throwable and `fail` like type class

so that is probably reason why complete stack trace is not visible

**Comment by justcoon** [comment]
hi @frevib 

have some additional informations 

if you call `ZIO.fail`, it will transformed to `Cause.Fail`

if you cal `ZIO.die`, it will transformed to `Cause.Die`

in case of zio default logger, `Cause.prettyPrint` is used

implementation of this function for `Cause.Fail` is more like `.toString`, so for throwable it will be `throwable.toString`

for `Cause.Die` it is using `throwable.getStackTrace` and `throwable.getCause` to print result, that is reason why stack trace is visible in this case

**Comment by justcoon** [comment]
hi @frevib,

I  had discussion with zio-core contributors,  

based on your questions, `Cause.prettyPrint` was changed (https://github.com/zio/zio/pull/7541), 

with this change `Cause.Fail` with throwable should be printed in same way like `Cause.Fail`

thank you

**Comment by frevib** [comment]
Thanks for the quick wrap up. Can we expect the change in the upcoming ZIO release?

**Comment by justcoon** [comment]
PR was merge, so it should be in next zio release, however I am not sure when it will be released, last zio release (2.0.4) was made 2 days ago

**Comment by justcoon** [comment]
@frevib 
zio 2.0.5 was released, it should contain changed `Cause.prettyPrint`
please let me know if it is ok for you, and also then if I can close this issue

**Comment by frevib** [comment]
It works in 2.0.5! Thanks for fixing.
