### ISSUE TITLE
SLFJ4 binding can drop log records about application startup failure

### ISSUE THREAD

**Issue by rtimush** [zio/zio-logging#616]
Can be reproduced with the following code:
```scala
object Main extends ZIOAppDefault {

  override val bootstrap: ZLayer[ZIOAppArgs, Any, Any] =
    Runtime.removeDefaultLoggers >>> SLF4J.slf4j

  def run: ZIO[Any, Throwable, Unit] =
    ZIO.dieMessage("Error") <&> ZIO.unit

}
```

What seems to happen is:
- ZIO runtime tries to log fiber errors concurrently, and this makes SLF4J create substitute loggers
- the application terminates before the actual logger is initialized, so SLF4J doesn't get a chance to print a warning about substitute loggers

If the `run` method is changed to 
```scala
  def run: ZIO[Any, Any, Unit] =
    (ZIO.dieMessage("Error") <&> ZIO.unit).sandbox.ignore *>
      ZIO.logInfo("info 1") *>
      ZIO.sleep(1.second) *>
      ZIO.logInfo("info 2")
```
then `info 2` is logged, `info 1` is not, but at least `slfj4` prints that a substitute logger was created and some log messages may be missing.

This can be a relatively common scenario, if the error happens when building a layer with ZLayer.make, something like:
```scala
  def run: ZIO[Any, Any, Unit] =
    ZIO.unit.provideLayer(
      ZLayer.make[A & B](
        ZLayer.fromZIO(ZIO.fail("failure").as(A())), // this failure will not be logged
        ZLayer.succeed(B())
      )
    )
```

**Comment by justcoon** [comment]
hi, thank you for report

it is look like that program will end sooner then slf4j log system is initialised and message logged, in cases when failure is first log in application
