### ISSUE TITLE
ZIO logging 2.1.8 causes SLF4j log replay

### ISSUE THREAD

**Issue by longliveenduro** [zio/zio-logging#631]
Since I upgraded from 2.1.7 to 2.1.8 I now get

```
core 05:19:04.684 [ZScheduler-Worker-12] DEBUG i.n.u.i.l.InternalLoggerFactory: [               ] Using SLF4J as the default logging framework
core[ERROR] SLF4J: A number (34) of logging calls during the initialization phase have been intercepted and are
core[ERROR] SLF4J: now being replayed. These are subject to the filtering rules of the underlying logging system.
core[ERROR] SLF4J: See also https://www.slf4j.org/codes.html#replay
core 05:19:04.689 [cluster-ClusterId{value='63cf5c38299dcf57bb36c807', description='null'}-localhost:27017] INFO  org.mongodb.driver.cluster: [               ] Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=13, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=32333373}
core 05:19:04.690 [ZScheduler-Worker-12] DEBUG i.n.util.internal.PlatformDependent0: [               ] -Dio.netty.noUnsafe: false
core 05:19:04.690 [ZScheduler-Worker-12] DEBUG i.n.util.internal.PlatformDependent0: [               ] Java version: 17

```
When I downgrade to 2.1.7 or use `LoggerFactory.getLogger("zio-slf4j-logger")` early, the replay goes away. 

I do have the `LoggerFactory.getLogger("zio-slf4j-logger")` hack from https://github.com/zio/zio-logging/pull/617. Maybe this is related?

**Comment by justcoon** [comment]
hello @longliveenduro 

thank you for report

this suppose to fix #616 

in general i think https://www.slf4j.org/codes.html#replay should not be major issue, based on my previous experience (not just with zio, but with slf4j in general) you can see those SLF4J error lines in case when application want to do some logging, and slf4j backend (logback, log4j ...) is not completely initialised yet ...

instead of this 3 SLF4J error lines (with 2.1.8), are there some any other issues? 

thank you

**Comment by longliveenduro** [comment]
Hi @justcoon. Thanks for coming back to me.
The problem does not appear in 2.1.7, so it must be related to a change from 2.1.7 to 2.1.8.

I see a lot more messages from ZIO (trying to access DirectBuffer etc), I just did cut the logs. It is really a lot, and I currently use the "hack" above to be able to use 2.1.8 without this replay issue. Let me know if you want to have the full replay.

Apart from that, everything works fine.

**Comment by justcoon** [comment]
hi @longliveenduro 

in relation to changes from 2.1.7 to 2.1.8

only `LoggerFactory.getLogger("zio-slf4j-logger")` was added, to invoke ASAP init of slf4j

in general in case of application which I updated with version 2.1.8, i did not noticed any strange behavior
but mostly i am using logback and relatively simple configuration with console appender

can you provide some additional information in relation to your app dependencies like

which slf4j logging backend you are using (logback, log4j,....), which version, logger configuration ...

maybe more log messages, which you think you should not see in relation to your logger configuration ...


thank you

**Comment by longliveenduro** [comment]
Hi @justcoon. While I was trying to gather the requested data, the problem did not occur any more when I removed my hack. So probably my failure, sorry! Will close this.
