### ISSUE TITLE
Official documentation not updated with latest changes

### ISSUE THREAD

**Issue by guizmaii** [zio/zio-logging#656]
Hey there :)

I noticed the new SLF4J v2 backend. Thanks for that ❤️

While reading the code of the PR, I've seen that there's a new doc page dedicated to it: https://github.com/zio/zio-logging/pull/639/files#diff-c913b24c611d897706f12ac23b2a095dfb1d3e353b5ef2d02e1375b716139870

I don't see this documentation in the doc website:
<img width="1904" alt="image" src="https://user-images.githubusercontent.com/1193670/218356751-5dbbc9f2-e80b-4caa-8d9f-fc8facbc3a89.png">

Cc @khajavi

**Comment by guizmaii** [comment]
Is done here: https://github.com/zio/zio/pull/7813

**Comment by khajavi** [comment]
@guizmaii 
I triggered a workflow to publish recent changes: https://github.com/zio/zio/actions/runs/4159642609

**Comment by guizmaii** [comment]
Thanks Milad ❤️
