### ISSUE TITLE
Base on log4zio?

### ISSUE THREAD

**Issue by leigh-perry** [zio/zio-logging#7]
At @jdegoes 's request, I have opened this as its own issue.

I have a logging library https://github.com/leigh-perry/log4zio that might be a useful starting point for zio-logging. Its main selling point is contravariant-functor-style composition of loggers. It is ZIO-based without dependencies on Cats or Scalaz.

### Modules

Currently there are two modules:

1. `core` contains the main abstraction, dependent only on ZIO.

1. `slf4j` provides for logging over conventional JVM-style frameworks.

## Design

There are two design points.

#### Error-free

The interface assumes that the user doesn't want to experience logging failures. Logging is most important under failure conditions, so it is best to log via a fallback mechanism rather than fail altogether.

To convey that the interface will not emit errors, all operations are in `UIO`.

**Update: I have exposed error-ful versions too - the error-free versions build on these, adding fallback handling to avoid emitting errors.**

#### Contravariant composition

The library lets the user create a new logging capability by composing refinements on top of a base logging implementation.

For example, if you have a simple-text console logger, Contravariant composition allows you to create a logger that includes a timestamp on every message. Or, it means that you can create a logger that encodes as JSON, writing the JSON data out to a string logger. Alternatively, you can create a logger that accepts only a specialised `SafeString` data type for its log messages. Implementing this is easy since the `SafeString` can be converted to `String` for the log-writing phase. Or perhaps all your log messages take the form of an integer code, and you want to be able to merely call `log.info(101)` to write whatever that means to your log.

```scala
final case class LogMedium[+E, A](log: A => IO[E, Unit]) {
  def contramap[B](f: B => A): LogMedium[E, B] =
    LogMedium[E, B](b => log(f(b)))

  def contramapM[E1 >: E, B](f: B => IO[E1, A]): LogMedium[E1, B] =
    LogMedium[E1, B](b => f(b).flatMap(log))

  def orElse[E2](that: => LogMedium[E2, A]): LogMedium[E2, A] =
    LogMedium[E2, A](a => log(a).catchAll(_ => that.log(a)))
}
```

### `LogMedium`

`LogMedium` conveys the basic abstraction of logging: a function from some `A` to `Unit`, for example taking a `String` and (effectfully) writing it somewhere.

`LogMedium[A]` is a contravariant functor, so it can be reused to implement another `LogMedium[B]` via `contramap`, so long as `B` can be converted to an `A`.

#### `TaggedLogMedium`

`TaggedLogMedium` is a derived `LogMedium` that encapsulates the conventional logging pattern, with a logging level (such as INFO) and timestamp. Addition of the level and timestamp info is also achieved by `contramap`-ing the additional level and timestamp tags onto a raw logger.

The implementation is [here](https://github.com/leigh-perry/log4zio/blob/master/modules/core/src/main/scala/com/leighperry/log4zio/LogMedium.scala#L52).

### `Log`

The second main component is `Log`. It is an implementation of the ZIO *service* pattern, and encapsulates a conventional logging API over the active configured `LogMedium`:

```scala
trait Log[E, A] {
  def log: Log.Service[E, A]
}

object Log {
  type SafeLog[A] = Log[Nothing, A]

  def log[E, A]: ZIO[Log[E, A], Nothing, Log.Service[E, A]] =
    ZIO.access[Log[E, A]](_.log)

  /**
   * An implementation of conventional logging with timestamp and logging level
   */
  trait Service[E, A] {
    def error(s: => A): IO[E, Unit]
    def warn(s: => A): IO[E, Unit]
    def info(s: => A): IO[E, Unit]
    def debug(s: => A): IO[E, Unit]
  }
  :
```

NOTE: logging is in `A`, allowing `SafeString` or even `Int` logging. In a fatuous examples of `Int` Logging:

```scala
object AppMain extends zio.App {

  def intLogger: UIO[Log[Int]] =
    Log.make[Int](intRendered(RawLogMedium.console))

  def intRendered(base: LogMedium[String]): LogMedium[Tagged[Int]] =
    base.contramap {
      m: Tagged[Int] =>
        val n: Int = m.message()
        "%-5s - %d:%s".format(m.level.name, n, "x" * n)
    }

  final case class AppEnv(log: Log.Service[Int]) extends Log[Int]

  override def run(args: List[String]): ZIO[zio.ZEnv, Nothing, Int] =
    for {
      logsvc <- intLogger
      log = logsvc.log

      pgm = Application.execute.provide(AppEnv(log))

      exitCode <- pgm.foldM(
        e => log.error(11) *> ZIO.succeed(1),
        _ => log.info(10) *> ZIO.succeed(0)
      )
    } yield exitCode
}

// The core application
object Application {
  val doSomething: ZIO[Log[Int], Nothing, Unit] =
    for {
      log <- Log.log[Int]
      _ <- log.info(1)
      _ <- log.info(2)
    } yield ()

  val execute: ZIO[Log[Int], Nothing, Unit] =
    for {
      log <- Log.log[Int]
      _ <- log.info(3)
      _ <- doSomething
      _ <- log.info(4)
    } yield ()
}
```
yields the output
```
INFO  - 3:xxx
INFO  - 1:x
INFO  - 2:xx
INFO  - 4:xxxx
INFO  - 10:xxxxxxxxxx
```

In this example, the `Int` version of a `LogMedium` is created by taking a raw `LogMedium` over ZIO `Console` and contramapping it into a `LogMedium[Tagged[Int]]`:

```
  def intRendered(base: LogMedium[String]): LogMedium[Tagged[Int]] =
    base.contramap {
      m: Tagged[Int] =>
        val n: Int = m.message()
        "%-5s - %d:%s".format(m.level.name, n, "x" * n)
    }
```

This silly rendering prints the integer value plus an 'x' that number of times, but it is meant to illustrate the idea that the `Int` value is available to the `LogMedium` logic and that Contravariant implementation of that logger can render it anyway it wants. Looking up an error code dictionary would be a more realistic way to go!

Opinions welcome :-)

**Comment by NeQuissimus** [comment]
I don't agree with the "error-free" design.
I understand it's convenient but you have code that can fail. Yet, your types convey that it cannot, which is effectively a lie. This is a slippery slope from effect to side-effect.

Personally, I also think it is awkward that one needs a `Log[A]` for every `A` that needs logging.
Looking through some of my smaller services, I'd end up with at least 3 or 4 of them every time.
Which, of course, means that I will really only ever use `Log[String]` and use `scalaz.Show` to turn things into `String` before logging them.
I wonder if there is a nicer way of doing this without depending on Scalaz or Cats.

**Comment by leigh-perry** [comment]
> I don't agree with the "error-free" design.
I understand it's convenient but you have code that can fail. Yet, your types convey that it cannot, which is effectively a lie. This is a slippery slope from effect to side-effect.

These are genuine `UIO`s. `Log` and `LogMedium` instances provide fallback so that no failures are emitted. For example, in the slf4j module, see `.catchAll` on [acquisition](https://github.com/leigh-perry/log4zio/blob/master/modules/slf4j/src/main/scala/com/leighperry/log4zio/slf4j/Slf4jLog.scala#L12) and on [use](https://github.com/leigh-perry/log4zio/blob/master/modules/slf4j/src/main/scala/com/leighperry/log4zio/slf4j/Slf4jLogMedium.scala#L23).

> Personally, I also think it is awkward that one needs a Log[A] for every A that needs logging.

The way I use this is to choose only one `A` for application logging, usually `String`, and then do all the logging in that, as you say. The parametricity is there to support other choices than `String`, for example a [safe string type](https://github.com/afsalthaj/safe-string-interpolation)

**Comment by leigh-perry** [comment]
The alternative to `UIO` is to give users the choice of error handling:
```scala
  trait Service[E, A] {
    def error(s: => A): IO[E, Unit]
    def warn(s: => A): IO[E, Unit]
    def info(s: => A): IO[E, Unit]
    def debug(s: => A): IO[E, Unit]
  }
```
and for those wanting unexceptional logging, separate out the `.catchAll` handling into another syntax layer, eg `throwableLogger.safely`.

**Comment by leigh-perry** [comment]
Update: I have exposed error-ful versions too - the error-free versions build on these, adding fallback handling to avoid emitting errors. For example [`consoleE`](https://github.com/leigh-perry/log4zio/blob/master/modules/core/src/main/scala/com/leighperry/log4zio/LogMedium.scala#L51) can emit errors, whereas `console` can not.

**Comment by jdegoes** [comment]
I think what we need to do is steal the concept of a contravariant `Logger`.

Currently we only have logging methods, no means to create a logger, and hence, since loggers are not really first-class values, no means to contramap them or compose them.

Unfortunately everything was merged while I was away, but I'll try to revisit what's in the repository as soon as I can and come up with some hybrid.

**Comment by leigh-perry** [comment]
Closing this issue as an alternative implementation has been merged.
