### ISSUE TITLE
Recommended usage in combination with ZLayer

### ISSUE THREAD

**Issue by ipsq** [zio/zio-logging#73]
I'm currently writing my first application based on `ZLayer` based on Pavels Sisojevs blog post ["From idea to product with ZLayer"](https://scala.monster/welcome-zio/). In his blog post he makes use of a self rolled logging service. Instead of rolling it myself, I used this project. So far so good. I create my own implementation classes with the following example dependencies:

```scala
class Live(httpClient: HttpClient.Service, logging: Logging.Service) extends GithubService.Service {
  ...
}
```

However, I find the syntax used for basic debug logging very convoluted. It looks like this:

```scala
def getRepos: Task[List[Repo]] = for {
  ...
  _ <- logging.logger.log(LogLevel.Debug)(body)
  ...
} yield repos
```

Something so simple requires me to look at the service definition again and again because I expect something simple as `logging.debug(body)`. Currently, there aren't any log level specific definitions on both the `Logging.Service` and the `LoggerLike` traits. They are however defined on the `log` package object. Using this would get my something like the following:

```scala
def getRepos: Task[List[Repo]] = (for {
  ...
  _ <- log.debug(body)
  ...
} yield repos).provideLayer(ZLayer.succeed(logging))
```

This also doesn't look like something that was intended. Am I completely missing something? Without `ZLayer` this would have looked like:

```scala
def getRepos: RIO[Logging with HttpClient, List[Repo]] = for {
  ...
  _ <- log.debug(body)
  ...
} yield repos
```

Should there be methods like `.debug` living in the `Logging.Service` definition or the `LoggerLike` definition?

**Comment by pshemass** [comment]
I haven't read his blog yet but in the projects that I'm using ZIO with layers I typically use combinators provided by ```ZLayer``` - ``++`` and ```>>>```.

with ```ZLayer``` your code will look 
```
def getRepos: RIO[zio.logging.Logging.Logging with HttpClient, List[Repo]] = for {
  ...
  _ <- log.debug(body)
  ...
} yield repos
```


```
object MyFirstApp extends zio.App {

  val logging = Logging.console{ case (_, line) => line }

  val dependencies = HttpClient.layer ++ logging

  val program = for {
    repo <- getRepos
    other <- getOtherCoolStuff
   ....
} yield ()

  def runMain(args: List[String]) =
    program.provideCustomLayer(dependencies).as(0)
```

you have couple of options how to create ```ZLayer``` with ```Logging```.
1. Use ```zio.logging.Logging.make``` and pass whatever function ```(LogContext, => String) => URIO[R, Unit]``` perform logging for you. it can be console, file or remote appender e.g. LogStash
2. Use ```zio.logging.Logging.console``` and pass function that renders string from log message. This function will render timestamp and log level for you.
3. you can use ```zio.logging.slf4j.Slf4jLogger.make``` and pass log message render function. this requires slf4j implementation and configuration.  


and this is recommended way. cc: @jdegoes

**Comment by psisoyev** [comment]
From what I see in the code of the current implementation of `zio-logging` (v0.2.5), it doesn't follow the module pattern. 
It looks like  `Logging` module should have a `Service` methods of `Logger` and maybe even more. I would like to see methods like `info`, `warn` etc on `Service` level that would simply be implemented as:
```
def info(line: => A): UIO[Unit] = log(LogLevel.Info)(line)
```
That kind of convenience method would simplify the usage of the library. But that's another topic. 

To solve the original issue I would expect `Logging` (or `Logger`) to be a module: 
```
object Logging {
  type Logging = Has[Service]
  trait Service {
    def info(line: => A): UIO[Unit]
   def log(level: LogLevel)(line: => A)
    // skipping the rest
  }
  
  def make[R](logger: (LogContext, => String) => URIO[R, Unit]): ZLayer[R, Nothing, Logging] = ???
  def console(format: (LogContext, => String) => String): ZLayer[Console with Clock, Nothing, Logging] = ???
  val ignore: Layer[Nothing, Logging] = ???
}
```

@ipsq What you could do in `Main` class now is to create zio logger like this:
```
val zioLoggerLayer: URLayer[Console with Clock, Has[Logger]] =
      Logging
        .console { case (_, line) => line }
        .map(logging => Has(logging.get.logger))
```

Then GitHub client Layer recipe should require `Has[Logger]`:
```
def live: URLayer[Has[Logger] with HttpClient, Has[Service]] = ???
```

And `Live` implementation needs to accept `zio.logging.Logger`: 
```
private[github] final case class Live(logger: Logger, httpClient: HttpClient.Service)
```
Please let me know if you need more information. 

Also, @pshemass if you want I could help you with moving to zio-logging to the module pattern

**Comment by ipsq** [comment]
Would the following `Logging` object definition be adhering to the module pattern set by ZIO?

```scala
object Logging {
  type Logging = Has[Logger]
  
  def console(
    format: (LogContext, => String) => String
  ): ZLayer[Console with Clock, Nothing, Logging] =
    make((context, line) =>
      for {
        date       <- currentDateTime.orDie
        level      = context.get(LogAnnotation.Level)
        loggerName = LogAnnotation.Name.render(context.get(LogAnnotation.Name))
        _          <- putStrLn(date.toString + " " + level.render + " " + loggerName + " " + format(context, line))
      } yield ()
    )

  val ignore: Layer[Nothing, Logging] =
    make((_, _) => ZIO.unit)

  def make[R](logger: (LogContext, => String) => URIO[R, Unit]): ZLayer[R, Nothing, Logging] =
    ZLayer.fromEffect(
      Logger.make(logger)
    )
}
```

If not then we could let `Logging.Service` extend `Logger` and proxy the methods from an underlying. Or even to keep the API backwards compatible, proxy on the `logger` method on the `Logging.Service` like so:

```scala
trait Service extends Logger {
  def logger: Logger

  def locally[R1, E, A](f: LogContext => LogContext)(zio: ZIO[R1, E, A]): ZIO[R1, E, A] =
    logger.locally(f)(zio)

  def log(line: => String): UIO[Unit] = logger.log(line)

  def logContext: UIO[LogContext] = logger.logContext
}
```

In combination with this, I'd like to propose the following methods being added to `LoggerLike`:

```scala
def fatal(line: => String): UIO[Unit =
  log(LogLevel.Fatal)(line)

def error(line: => String): UIO[Unit =
  log(LogLevel.Error)(line)

def warn(line: => String): UIO[Unit =
  log(LogLevel.Warn)(line)

def info(line: => String): UIO[Unit =
  log(LogLevel.Info)(line)

def debug(line: => String): UIO[Unit =
  log(LogLevel.Debug)(line)

def trace(line: => String): UIO[Unit =
  log(LogLevel.Trace)(line)
```

With the following being optional:

```scala
def throwable(line: => String, t: Throwable): UIO[Unit] =
  error(line, Cause.die(t))

def error(line: => String, cause: Cause[Any]): UIO[Unit] =
  log(LogLevel.Error)(line + System.lineSeparator() + cause.prettyPrint)
```

**Comment by jdegoes** [comment]
I think a few things could be done:

1. Add `fine` / `debug` / etc. shorthands to the `LoggerLike` trait.
2. Add all methods of `Logger` trait to the `Logger` companion object, as helpers that access a logger methods from the environment (`Has[Logger]`). This will make it more consistent with other ZIO projects.
3. Have all `log.*` helper methods just delegate to the methods inside `Logger` companion object.
4. More aggressive factor creations of logger in terms of `ZLayer`, e.g. `console` should be `ZLayer[Console, Nothing, Logger]`, and there can exist zlayer constructors for `Logger` for SLF4j, etc.

**Comment by pshemass** [comment]
https://github.com/zio/zio-logging/pull/76

added methods to ```LoggerLike```

**Comment by pshemass** [comment]
@psisoyev I'm still trying to understand why do you think that doing this
```
object Logging {
  type Logging = Has[Service]
  trait Service {
    def info(line: => A): UIO[Unit]
   def log(level: LogLevel)(line: => A)
    // skipping the rest
  }
  
}
```

is better to do this
```
type Logging = Has[Logging.Service]

  trait Service {
    def logger: Logger
  }

```
Could you explain this for me?

**Comment by pshemass** [comment]
@ipsq you are right this is not recommended if you build service layer. I added more methods to logger that should be #76 merged soon.

**Comment by pshemass** [comment]
I believe those suggestions has been addressed.
