### ISSUE TITLE
class TypesafeConfigProvider is not found

### ISSUE THREAD

**Issue by gvlpedro** [zio/zio-logging#791]
I am trying to use the File logger from this example: https://zio.dev/zio-logging/file-logger#file-logger

This class is not found: import zio.config.typesafe.TypesafeConfigProvider

I used the following dependencies:
`  "dev.zio" %% "zio-logging" % "2.1.15",
  "dev.zio" %% "zio-config" % "3.0.7",`

am I wrong? or I missing out something? thanks in advance

**Comment by justcoon** [comment]
hello @gvlpedro 
i think you have to use latest one https://github.com/zio/zio-config/releases/tag/v4.0.0-RC16
as there were noticeable changes due to integration of main Config interface directly to zio core library

**Comment by gvlpedro** [comment]
thanks @justcoon but I have the same problem with that version

**Comment by justcoon** [comment]
oh sorry, forgot to mention, that you need to have

```
"dev.zio" %% "zio-config-typesafe" % "4.0.0-RC16
```

**Comment by gvlpedro** [comment]
thanks @justcoon, now works !
