### ISSUE TITLE
Suggestion: ZIO Log Ops to improve usability

### ISSUE THREAD

**Issue by renancaju** [zio/zio-logging#91]
I find it that logging sometimes make your code more difficult to read, since you normally interleave commands with logging operations. In my most recent code I've created a `ZIOLogOps` implicit class that gives us what I consider a more readable alternative to that.

```scala
implicit class ZIOLogOps[R <: Logging with ZUUID, E, A](val z: ZIO[R, E, A]) extends AnyVal {
    def withCorrelationId: ZIO[R, E, A] =
      for {
        uuid  <- ZUUID.uuid
        result <- log.locally(_.annotate(LogAnnotation.CorrelationId, Some(uuid)))(z)
      } yield result

    def withLoggerName(name: String): ZIO[R, E, A] =
      log.locally(_.annotate(LogAnnotation.Name, name :: Nil))(z)

    def logInfo(f: A => String): ZIO[R, E, A] =
      z.tap(a => log.info(f(a)))

    def logError(f: E => String): ZIO[R, E, A] =
      z.tapError(e => log.error(f(e)))

    def logFold(fe: E => String, fa: A => String): ZIO[R, E, A] =
      z.logError(fe).logInfo(fa)
  }
```

A usage example would be:

```scala
val pipe = for {
  user <- UserRepository.findById(userId).logError(e => s"Error finding user: $e")
  credit <- BalanceRepository.getBalanceByUserId(userId).logInfo(b => s"Balance of $b found")
} yield ()

pipe
  .withLoggerName("UserBalanceService")
  .withCorrelationId
```

The current alternatives without this syntax would be:

```scala
val pipe = for {
  user <- UserRepository.findById(userId).tapError(e => log.error(s"Error finding user: $e"))
  credit <- BalanceRepository.getBalanceByUserId(userId).tap(b => log.info(s"Balance of $b found"))
} yield ()

for {
  correlationId <- ZUUID.uuid
  _ <- log.locally(_.annotate(LogAnnotation.Name, "UserBalanceService" :: Nil)
.annotate(LogAnnotation.CorrelationId, Some(uuid)))(pipe)  
} yield ()
```

I find the first alternative cleaner. What do you think? Would it be interesting to have some `zio.logging.syntax` package shipped with the library?

**Comment by renancaju** [comment]
It would still need a standard way to generate UUID's with the ZIO library, which I don't think there is right now.

**Comment by pshemass** [comment]
I see what you mean but I'm not exactly convinced to your approach
in pipe example
```
val pipe = for {
  user <- UserRepository.findById(userId).logError(e => s"Error finding user: $e")
  credit <- BalanceRepository.getBalanceByUserId(userId).logInfo(b => s"Balance of $b found")
} yield ()
```

I like ```logError``` part but not ```logInfo``` part. I would write this 
```
val pipe = for {
  user <- UserRepository.findById(userId).logError(e => s"Error finding user: $e")
  credit <- BalanceRepository.getBalanceByUserId(userId)
  _ <- log.info(b => s"Balance of $b found")
} yield ()
```

for `withCorrelatationId` and `withLoggerName` I would say no. I prefer to have something like
```
import LogAnnotation._
log.annotate(CorrelationId(), Name("UserBalanceService"), OtherRandomAnnotation("foo")) {
  pipe
}
```

what do you think @renancaju about this?

**Comment by renancaju** [comment]
About the `logInfo` bit, yeah, I guess it's not great. But imagine you just want to log the result like this:

```scala
_ <- BalanceRepository.getBalanceByUserId(userId).logInfo(_.toString)
```

I feel it would be better than:

```scala
balance <- BalanceRepository.getBalanceByUserId(userId)
_ <- log.info(balance.toString)
```

About the annotation composability you proposed, you mean making `LogAnnotation` a trait and creating case classes extending that trait like `CorrelationId`, `Name`, etc? Or those case classes would extends some other trait that would be like LogAnnotation recipes?

One thing I like better in the syntax I proposed is that you avoid nesting and give emphasis to the business logic (the `pipe`) instead of logging (which is the first thing that appears if you use the current syntax). 

Of course, these are opinions based on my usage only and totally subjective. Other people might feel differently.

**Comment by pshemass** [comment]
as you mentioned this is all subjective. For me `for` in scala or `do` in haskell ware created to help organize code in sequence vertically so argument with one liner in `for` doesn't resonate with me :)

even with today structure you can do this
```
log.locally(CorrelationId(Some(uuid)).andThen(Name("loggerName" :: Nil)){ pipe }
```
maybe it's a matter to add shortcut for that. What do you think?

**Comment by renancaju** [comment]
Sorry, I guess I missed the `apply` method on `LogAnnotation` that returns a `LogContext => LogContext`, which makes everything compose nicely... 

I guess the only improvement in my suggestions would be regarding the generation of `UUID`s automatically. But since there is no standard way of doing so with ZIO, I guess it would not be in the scope of zio-logging. Maybe an external zio-utils package could solve it.

Sorry to waste your time! For me it was really valuable, cause I learned something from this interaction 😄
